AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Naming/FileName:
  Exclude:
    - lib/capybara-lightpanda.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/OneClassPerFile:
  Enabled: true
  Exclude:
    - examples/**/*.rb

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - lib/capybara/lightpanda/binary.rb
    - lib/capybara/lightpanda/browser.rb
    - lib/capybara/lightpanda/client/web_socket.rb
    - lib/capybara/lightpanda/driver.rb
    - lib/capybara/lightpanda/node.rb
    - lib/capybara/lightpanda/process.rb
    - spec/**/*
    - examples/**/*.rb

Metrics/MethodLength:
  Max: 30
  Exclude:
    - examples/**/*.rb

Metrics/AbcSize:
  Max: 25
  Exclude:
    - examples/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 7

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - Rakefile
    - examples/**/*.rb

Lint/EmptyBlock:
  Exclude:
    - spec/**/*

Lint/UselessConstantScoping:
  Enabled: false
